#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push hook: npm run build..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Push aborted."
  exit 1
fi

echo "Build successful. Proceeding with push."
exit 0
